### PR TITLE
[BUG] Fix parse a non email

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey @taitems,

I'm sending this PR is to fix a small bug when try to parse a non email.

It is trigging an error: `Cannot read properties of undefined (reading 'split')` in the code:

```js
emailToName.process('contact')
```

I also added tests and upgrade the packages.

Thanks.

### CODE REVIEW

**Comment by taitems** [comment]
Great. Will bump test suite so it can run properly. Hopefully attack tonight.

**Comment by taitems** [comment]
Apologies, CI was having issues with very dated node version. Could you please you rebase?

**Comment by felipehertzer** [comment]
Hey @taitems thanks, I just rebase the branch.

**Comment by taitems** [comment]
Merged. Thanks for your contribution :)

**Comment by felipehertzer** [comment]
Hey @taitems, 

Sorry, I think it is missing an npm run build or something like that.

I'm receiving this error `Could not resolve "./dist" from "./dist?commonjs-external"`.

I can see that is missing the folder `dist` when I install it using yarn

**Comment by taitems** [comment]
Okay, please try again with `2.0.6`.

This is an older project that doesn't have very good CI/CD. So I was manually running `npm publish` and forgetting to build first.

I now have a `npm run release` task which will `npm run build` then `npm release`. I'll need to revisit this some stage and make it autodeploy.

**Comment by felipehertzer** [comment]
Yeah, it is working again, thanks.

**Comment by taitems** [comment]
Thanks for following up. I will try to implement better CI/CD but I can't make any promises.

**Pull request merged**
